flowchart LR
%% Authorization
가맹점 수신[가맹점 수신]
UH_TRANS_HISTORY  거래  수신 기록([UH_TRANS_HISTORY  거래  수신 기록])
UH_MERCHANT  가맹점([UH_MERCHANT  가맹점])
UH_MERCHANT_KEY  가맹점 인증 정보 테이블([UH_MERCHANT_KEY  가맹점 인증 정보 테이블])
UT_MERCHANT_SVC 가맹점+원천사 테이블([UT_MERCHANT_SVC 가맹점+원천사 테이블])
UH_CPID([UH_CPID])
승인[승인]
망취소[망취소]
UH_TRANS_FAIL 오류 발생 기록([UH_TRANS_FAIL 오류 발생 기록])
UH_TRANS 통합 거래원장([UH_TRANS 통합 거래원장])
UH_TRANS_CARD_KOR 신용카드 거래 원장([UH_TRANS_CARD_KOR 신용카드 거래 원장])
전송[전송]
가맹점 수신 --> |연결 1| UH_TRANS_HISTORY  거래  수신 기록
UH_TRANS_HISTORY  거래  수신 기록 --> |연결 2| UH_MERCHANT  가맹점
UH_MERCHANT  가맹점 --> |연결 3| UH_MERCHANT_KEY  가맹점 인증 정보 테이블
UH_MERCHANT_KEY  가맹점 인증 정보 테이블 --> |연결 4| UT_MERCHANT_SVC 가맹점+원천사 테이블
UT_MERCHANT_SVC 가맹점+원천사 테이블 --> |연결 5| UH_CPID
UH_CPID --> |연결 6| 승인
승인 --> |연결 7| 망취소
승인 --> |연결 8| UH_TRANS 통합 거래원장
UH_TRANS 통합 거래원장 --> |연결 9| UH_TRANS_CARD_KOR 신용카드 거래 원장
UH_TRANS_CARD_KOR 신용카드 거래 원장 --> |연결 10| 전송
망취소 --> |연결 13| UH_TRANS_FAIL 오류 발생 기록
