flowchart LR
%% 재정산 플로우
가맹점["가맹점"]
대행사["대행사"]
에이전시["에이전시"]
재정산시스템[재정산시스템]
settle_db([settle_db])
데몬[데몬]
가맹점 --> |재정산 등록| 재정산시스템
대행사 --> |재정산 등록| 재정산시스템
에이전시 --> |재정산 등록| 재정산시스템
재정산시스템 --> |재정산등록| settle_db
데몬 --> |등록된 정산정보 실행| settle_db
